language: node_js
cache:
  yarn: false
  npm: false
services:
  - docker
addons:
  postgresql: "10"
install: yarn install
env:
  - NODE_ENV="travis" DATABASE_URL="postgres://postgres:postgres@localhost:5432/travis"
before_script:
  - yarn db:drop || true && yarn db:create && yarn db:migrate
script:
  - yarn lint && yarn test
after_success: yarn coverage
notifications:
  email:
    recipients:
      - martin.salias@kleer.la
deploy:
  - provider: heroku
    skip_cleanup: true
    api_key:
      secure: dzymJmmJpP1nX/4AzcS+230/RPilqIVwAa+JfqvrP7cMU7Toj5JBMUKG5ZXogJxzMQZkdKvYGUCadMjEBmjfei5oBFRfL7a3G+lJstNVJHMaU7KBeaD0zGOXKkjUpRe40iq+qb+yf14w9kSf8vu1WqoSSUNZehqdz57HShufMAsjWeo+zb3RxfcKrzYL1KTyuyHaqnhb9RNo2z0ZJ5wFdPZUiPvH4lXHkmYv+pTjbtUAtLpFLSX5Ep+7h0G2pdoywr6IX43y3CEd5kaXb/2GmwDxq7uWBS1YI8RnoH7htIOR6+kxFw9P+uzYLb+7dbXi6P6BYRo8PFENOYOSwrVK1lMCewCiSiUh6UBOdV7/dOIs+iBl44wZwLeEPxcWlSzFn5SNWqd8Atd64hYRq1ta258tbg50JDkL+gZnI2u6p2wROTnSW96K6dTim0ApvjzAQrTv+UwhuEwSZ+4EWIIqQf9p2hhSfV4iBWlj2pxDnH15tSxrdlT5vLBViNoAPiz1WvEukVC05YYKNThTEDhfirGze6AAJlmbza3zpHb+Xe9+rSKQYS6HHDeW29HlLUKDTEtB4gaLHWptHSbxzXZ7r4kUXaOy03P6vcswZ3D7oyvbvf50+XXEyvlMtQi/wx7jE/HHKhfsWHnYq2sqmSCtAtUctBlMZk7X0hUAaI2Mpu4=
    app: nahual-datos-voluntaries
    on:
      branch: production
      repo: taller-de-desarrollo-proyectos-III/back-end
    run:
      - "yarn install && yarn build:src && yarn db:migrate"
